# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_JXGUnsucDQn8xn3GJZ4L-bRAEthrIhc
"""

import pandas as pd
import numpy as np

# Create random values using NumPy
np.random.seed(42)  # Set a seed for reproducibility
data = np.random.randn(4, 4)  # Generate random values with a normal distribution

# Create DataFrame
df = pd.DataFrame(data, columns=['Feature 1', 'Feature 2', 'Feature 3', 'Feature 4'])
print(df)

import pandas as pd
import numpy as np

# Create random values using NumPy
np.random.seed(42)  # Set a seed for reproducibility
data = np.random.randn(4, 4)  # Generate random values with a normal distribution

# Create DataFrame
df = pd.DataFrame(data, columns=['Feature 1', 'Feature 2', 'Feature 3', 'Feature 4'])

# Rename column names
df.rename(columns={'Feature 1': 'Random value 1',
                   'Feature 2': 'Random value 2',
                   'Feature 3': 'Random value 3',
                   'Feature 4': 'Random value 4'}, inplace=True)

print(df)

import pandas as pd
import numpy as np

# Create random values using NumPy
np.random.seed(42)  # Set a seed for reproducibility
data = np.random.randn(4, 4)  # Generate random values with a normal distribution

# Create DataFrame
df = pd.DataFrame(data, columns=['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4'])

# Get descriptive statistics
statistics = df.describe()

print(statistics)

import pandas as pd
import numpy as np

# Create random values using NumPy
np.random.seed(42)  # Set a seed for reproducibility
data = np.random.randn(4, 4)  # Generate random values with a normal distribution

# Create DataFrame
df = pd.DataFrame(data, columns=['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4'])

# Check for null values
null_values = df.isnull().sum()

# Get data types of columns
data_types = df.dtypes

print("Null values:\n", null_values)
print("\nData types:\n", data_types)

import pandas as pd
import numpy as np

# Create random values using NumPy
np.random.seed(42)  # Set a seed for reproducibility
data = np.random.randn(4, 4)  # Generate random values with a normal distribution

# Create DataFrame
df = pd.DataFrame(data, columns=['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4'])

# Display columns using .loc method
columns_loc = df.loc[:, ['Random value 2', 'Random value 3']]
print("Using .loc method:\n", columns_loc)

# Display columns using .iloc method
column_indices = [1, 2]  # Indices of 'Random value 2' and 'Random value 3' columns
columns_iloc = df.iloc[:, column_indices]
print("\nUsing .iloc method:\n", columns_iloc)